sudo: required
services:
- docker

addons:
  apt:
    packages:
    - nginx

before_install:
- gem install mustache

language: bash

install:
- travis_wait 30 bash install_bootstrap --script
- docker-compose version
# validate the nginx configuration files using nginx via docker
- docker run -v $PWD/config/default.nginx_http.conf:/etc/nginx/conf.d/default.conf nginx:1.13.1 nginx -t -c /etc/nginx/nginx.conf
- docker run -v $PWD/config/default.nginx_http.shared.conf:/etc/nginx/conf.d/default.conf nginx:1.13.1 nginx -t -c /etc/nginx/nginx.conf
