version: '2'

services:
#  elasticsearch:
#    image: 312767926603.dkr.ecr.ca-central-1.amazonaws.com/composesetup/elasticsearch:latest
#    build:
#      context: .
#      dockerfile: config/Dockerfile_elasticsearch
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    mem_limit: 1073741824
#    volumes:
#      - esdata1:/usr/share/elasticsearch/data
#    expose:
#      - "9200"
#      - "9300"
#    logging:
#      driver: awslogs
#      options:
#        awslogs-group: alpha-elasticsearch
#        awslogs-region: ca-central-1
#        awslogs-stream-prefix: dockstore

  webservice: 
    image: 312767926603.dkr.ecr.ca-central-1.amazonaws.com/composesetup/webservice:latest
    build:
      context: .
      dockerfile: config/Dockerfile_webservice
    restart: always
#    depends_on:
#      - elasticsearch
    logging:
      driver: awslogs
      options:
        awslogs-group: alpha-webservice
        awslogs-region: ca-central-1
        awslogs-stream-prefix: dockstore

  nginx_http:
    image: 312767926603.dkr.ecr.ca-central-1.amazonaws.com/composesetup/nginx_http:latest
    build:
      context: .
      dockerfile: config/Dockerfile_nginx_http
    restart: always
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: alpha-http
        awslogs-region: ca-central-1
        awslogs-stream-prefix: dockstore

  nginx_dockstore:
    image: 312767926603.dkr.ecr.ca-central-1.amazonaws.com/composesetup/nginx_dockstore:latest
    build:
      context: .
      dockerfile: config/Dockerfile_nginx_dockstore
    restart: always
    links:
      - webservice
    ports:
      - "8443:8080"
      - "443:4200"
    logging:
      driver: awslogs
      options:
        awslogs-group: alpha-nginx-dockstore
        awslogs-region: ca-central-1
        awslogs-stream-prefix: dockstore

#volumes:
#  esdata1:
