version: '2'

services:
  postgres:
    image: postgres:9.6.10
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    expose: 
      - "5432"
    logging:
      driver: "awslogs"
      options:
        awslogs-group: ${LOG_GROUP_NAME}
        awslogs-stream: "postgres"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    restart: always
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    expose:
      - "9200"
      - "9300"
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    logging:
      driver: "awslogs"
      options:
        awslogs-group: ${LOG_GROUP_NAME}
        awslogs-stream: "elasticsearch"

  migration: 
    build:
      context: .
      dockerfile: config/Dockerfile_webservice
    depends_on:
      - postgres
    volumes:
      - log_volume:/dockstore_logs
      - ./config/web.yml:/web.yml
    command: ["dockerize", "-wait", "tcp://postgres:5432", "-timeout", "60s", "./init_migration.sh"]
    logging:
      driver: "awslogs"
      options:
        awslogs-group: ${LOG_GROUP_NAME}
        awslogs-stream: "migration"

  webservice: 
    build:
      context: .
      dockerfile: config/Dockerfile_webservice
    restart: always
    depends_on:
      - postgres
      - elasticsearch
      - migration
    volumes:
      - log_volume:/dockstore_logs
      - ./config/web.yml:/web.yml
    expose:
      - "8081"
    logging:
      driver: "awslogs"
      options:
        awslogs-group: ${LOG_GROUP_NAME}
        awslogs-stream: "webservice"

  nginx_http:
    image: nginx:1.13.1
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/default.nginx_http.conf:/etc/nginx/conf.d/default.conf:ro
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
  #    - ./self-signed:/self-signed
    logging:
      driver: "awslogs"
      options:
        awslogs-group: ${LOG_GROUP_NAME}
        awslogs-stream: "nginx_http"

# re-enable if we go down the route of these metrics going into ELK
#  metricbeat:
#    image: docker.elastic.co/beats/metricbeat:6.4.0
#    user: root
#    restart: always
#    depends_on:
#      - webservice
#      - postgres
#    volumes:
#      - /proc:/hostfs/proc:ro
#      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
#      - /:/hostfs:ro
#      - ./config/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
#    command:
#      - "--strict.perms=false"
#      - "-system.hostfs=/hostfs"
#    logging:
#      driver: "awslogs"
#      options:
#        awslogs-group: ${LOG_GROUP_NAME}
#        awslogs-stream: "metricbeat"

volumes:
  log_volume: 
  certs:
  certs-data:
  esdata1:
    driver: local
