version: '2'
services:
  elasticsearch-logstash:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    restart: always
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1500m -Xmx1500m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata2:/usr/share/elasticsearch/data
      - ./staticConfig/elasticsearchLogstash.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./essnapshot:/mount/backups
  logstash:
    image: docker.elastic.co/logstash/logstash:6.4.0
    restart: always
    depends_on:
      - elasticsearch-logstash
    volumes:
      - ./staticConfig/logsToElastic.conf:/usr/share/logstash/pipeline/logsToElastic.conf
    environment:
      XPACK_MONITORING_ELASTICSEARCH_URL: "elasticsearch-logstash:9200"
    ports:
      - "5055:5055"
      - "5066:5066"
  kibana:
    build:
      context: .
      dockerfile: templates/kibanaDockerfile
    restart: always
    volumes:
      - ./staticConfig/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch-logstash
    environment:
      XPACK_SECURITY_ENABLED: "false"
  elastalert:
    image: bitsensor/elastalert:0.0.14
    environment:
      ES_HOST: "elasticsearch-logstash"
    depends_on:
      - elasticsearch-logstash
    restart: always
    ports:
      - "3030:3030"
    volumes:
      - ./config/rules:/opt/elastalert/rules
volumes:
  esdata2:
    driver: local
