version: '2'
services:
  elasticsearch-logstash:
    build:
      context: .
      dockerfile: templates/esDockerfile
    restart: always
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1500m
    ports:
      - "9200:9200"
    expose:
      - "9300"
    volumes:
      - ./config/jvm.options.es:/usr/share/elasticsearch/config/jvm.options
      - esdata2:/usr/share/elasticsearch/data
      - ./staticConfig/elasticsearchLogstash.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./essnapshot:/mount/backups
        #    command: ["dockerize", "-wait-retry-interval", "60s", "-timeout", "3600s",  "-wait", "tcp://kibana:5601", "/usr/local/bin/docker-entrypoint.sh"]
    logging:
      driver: "awslogs"
      options:
        awslogs-group: ${LOG_GROUP_NAME}
        awslogs-stream: "elasticsearch-logstash"
  logstash:
    build:
      context: .
      dockerfile: templates/logstashDockerfile
    restart: always
    depends_on:
      - elasticsearch-logstash
    volumes:
      - ./staticConfig/logsToElastic.conf:/usr/share/logstash/pipeline/logsToElastic.conf
      - ./config/jvm.options.logstash:/usr/share/logstash/config/jvm.options
    environment:
      - XPACK_MONITORING_ELASTICSEARCH_URL=elasticsearch-logstash:9200
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "5055:5055"
      - "5066:5066"
    mem_limit: 1g
    #    command: ["dockerize", "-wait-retry-interval", "60s", "-timeout", "3600s", "-wait", "tcp://kibana:5601", "/usr/local/bin/docker-entrypoint"]
    logging:
      driver: "awslogs"
      options:
        awslogs-group: ${LOG_GROUP_NAME}
        awslogs-stream: "logstash"

  kibana:
    build:
      context: .
      dockerfile: templates/kibanaDockerfile
    restart: always
    volumes:
      - ./staticConfig/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "35943:5601"
    depends_on:
      - elasticsearch-logstash
    environment:
      -  XPACK_SECURITY_ENABLED=false
      -  NODE_OPTIONS=--max_old_space_size=800
    mem_limit: 1g
    logging:
      driver: "awslogs"
      options:
        awslogs-group: ${LOG_GROUP_NAME}
        awslogs-stream: "kibana"

  elastalert:
    image: bitsensor/elastalert:1.0.0
    environment:
      ES_HOST: "elasticsearch-logstash"
    depends_on:
      - elasticsearch-logstash
    restart: always
    expose:
      - "3030"
    volumes:
      - ./config/rules:/opt/elastalert/rules
      - ./staticConfig/elastalert.yaml:/opt/elastalert/config.yaml
      - ./staticConfig/elastalert.config-test.yaml:/opt/elastalert/config-test.yaml
      - ./staticConfig/elastalert.config.json:/opt/elastalert-server/config/config.json
    mem_limit: 500m
    logging:
      driver: "awslogs"
      options:
        awslogs-group: ${LOG_GROUP_NAME}
        awslogs-stream: "elastalert"

volumes:
  esdata2:
    driver: local
