version: '2'


services:
  postgres:
    image: postgres:9.6
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    expose: 
      - "5432"

  elasticsearch:
    image: elasticsearch:5.5
    expose:
      - "9200"
      - "9300"

  webservice: 
    build:
      context: .
      dockerfile: config/Dockerfile_webservice
    restart: always
    depends_on:
      - postgres
      - elasticsearch
    volumes:
      - log_volume:/dockstore_logs
      - ./config/web.yml:/web.yml
  ui1:
    build:
      context: .
      dockerfile: config/Dockerfile_ui1
    volumes:
      - log_volume:/dockstore_logs
      - ./config/webservice.js:/dockstore-ui/app/scripts/services/webservice.js
      - ui1_content:/dockstore-ui/dist

  ui2:
    build:
      context: .
      dockerfile: config/Dockerfile_ui2
    volumes:
      - log_volume:/dockstore_logs
      - ./config/dockstore.model.ts:/dockstore-ui2/src/app/shared/dockstore.model.ts
      - ui2_content:/dockstore-ui2/real_dist

  nginx_http:
    image: nginx:1.13.1
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/default.nginx_http.conf:/etc/nginx/conf.d/default.conf:ro
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt

  nginx_https: 
    image: nginx:1.13.1
    restart: always
    depends_on:
      - ui1
      - ui2
      - webservice
    ports:
      - "8443:8080"
      - "9000:9000"
      - "443:4200"
    volumes:
      - ui1_content:/usr/share/nginx/html1:ro
      - ui2_content:/usr/share/nginx/html2:ro
      - ./config/default.nginx_https.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/default.nginx_https.shared.conf:/etc/nginx/conf.d/default.nginx_https.shared.conf:ro
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt

volumes:
  log_volume: 
  ui1_content:
  ui2_content:
  certs:
  certs-data:
