version: '2'
services:
  elasticsearch-logstash:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    restart: always
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./config/elasticsearchLogstash.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  logstash:
    image: docker.elastic.co/logstash/logstash:6.4.0
    restart: always
    depends_on:
      - elasticsearch-logstash
    volumes:
      - ./config/logsToElastic.conf:/usr/share/logstash/pipeline/logsToElastic.conf
    environment:
      XPACK_MONITORING_ELASTICSEARCH_URL: "elasticsearch-logstash:9200"
    ports:
      - "5055:5055"
  kibana:
    build:
      context: .
      dockerfile: kibanaDockerfile
    restart: always
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch-logstash
    environment:
      XPACK_SECURITY_ENABLED: "false"
  elastalert:
    image: bitsensor/elastalert:latest
    environment:
      ES_HOST: "elasticsearch-logstash"
    depends_on:
      - elasticsearch-logstash
    restart: always
    ports:
      - "3030:3030"
    volumes:
      - ./config/rules:/opt/elastalert/rules
