version: '2'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.1.3
    restart: always
    depends_on:
      - elasticsearch
    volumes:
      - ./config/logsToElastic.conf:/usr/share/logstash/pipeline/logsToElastic.conf
    expose:
      - "5055" 

