version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    restart: always
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data
    expose:
      - "9200"
      - "9300"
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.1.3
    restart: always
    depends_on:
      - elasticsearch
    volumes:
      - ./config/logsToElastic.conf:/usr/share/logstash/pipeline/logsToElastic.conf
    ports:
      - "5055:5055"
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    restart: always
    ports:
     - "5601:5601"
    depends_on:
     - elasticsearch

