metricbeat.modules:
- module: system
  metricsets: ["cpu", "load", "memory", "network", "process", "process_summary", "core", "diskio", "socket"]
  processes: ['.*']
  process.include_top_n:
    by_cpu: 5
    by_memory: 5
  period: 10s
  cpu.metrics:  ["percentages"]
  core.metrics: ["percentages"]

- module: system
  period: 1m
  metricsets:
    - filesystem
    - fsstat
  processors:
  - drop_event.when.regexp:
      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'

- module: system
  period: 15m
  metricsets:
    - uptime
- module: postgresql
  enabled: true
  metricsets:
    # Stats about every PostgreSQL database
    - database

    # Stats about the background writer process's activity
    - bgwriter

    # Stats about every PostgreSQL process
    - activity

  period: 10s

  # The host must be passed as PostgreSQL URL. Example:
  # postgres://localhost:5432?sslmode=disable
  # The available parameters are documented here:
  # https://godoc.org/github.com/lib/pq#hdr-Connection_String_Parameters
  hosts: ["postgres://postgres:5432/postgres"]

  # Username to use when connecting to PostgreSQL. Empty by default.
  username: postgres

  # Password to use when connecting to PostgreSQL. Empty by default.
  password: postgres

- module: dropwizard
  metricsets: ["collector"]
  period: 10s
  hosts: ["http{{#HTTPS}}s{{/HTTPS}}://{{ DOMAIN_NAME }}:8081"]
  metrics_path: /metrics/metrics
  namespace: example
  enabled: true

output.elasticsearch:
  hosts: {{ LOGSTASH_HOST }}:9200
  username: "elastic"
  password: "changeme"
setup.kibana:
  host: {{ LOGSTASH_HOST }}:5601
setup.dashboards.enabled: true
logging.to_files: true
logging.to_syslog: false
logging.files:
  path: /var/log/metricbeat
  name: metricbeat.log
  keepfiles: 2
  permissions: 0644
xpack.monitoring.enabled: true
